export const CREATE_DIARY_REQUEST = "CREATE_DIARY_REQUEST";
export const CREATE_DIARY_SUCCESS = "CREATE_DIARY_SUCCESS";
export const CREATE_DIARY_ERROR = "CREATE_DIARY_ERROR";
export const CREATE_DIARY_RESET = "CREATE_DIARY_RESET";

export const GET_DIARY_REQUEST = "GET_DIARY_REQUEST";
export const GET_DIARY_SUCCESS = "GET_DIARY_SUCCESS";
export const GET_DIARY_ERROR = "GET_DIARY_ERROR";
export const GET_DIARY_RESET = "GET_DIARY_RESET";

export const GET_DIARIES_REQUEST = "GET_DIARIES_REQUEST";
export const GET_DIARIES_SUCCESS = "GET_DIARIES_SUCCESS";
export const GET_DIARIES_ERROR = "GET_DIARIES_ERROR";
export const GET_DIARIES_RESET = "GET_DIARIES_RESET";

export const UPDATE_DIARY_REQUEST = "UPDATE_DIARY_REQUEST";
export const UPDATE_DIARY_SUCCESS = "UPDATE_DIARY_SUCCESS";
export const UPDATE_DIARY_ERROR = "UPDATE_DIARY_ERROR";
export const UPDATE_DIARY_RESET = "UPDATE_DIARY_RESET";

export const DELETE_DIARY_REQUEST = "DELETE_DIARY_REQUEST";
export const DELETE_DIARY_SUCCESS = "DELETE_DIARY_SUCCESS";
export const DELETE_DIARY_ERROR = "DELETE_DIARY_ERROR";
export const DELETE_DIARY_RESET = "DELETE_DIARY_RESET";
